server:
  port: 8083
  servlet:
    context-path: /p2
    
spring:
  application: 
    name: paglipay-java-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://paglipay-postgres.postgres.database.azure.com:5432/postgres
    username: paglipay@paglipay-postgres
    password: PAssw0rd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web:
      exposure:
        include:
          - "beans"
          - "health"
          - "info"
   